#ifndef MANTIDQTCUSTOMINTERFACES_DATACOMPARISONVIEW_H_
#define MANTIDQTCUSTOMINTERFACES_DATACOMPARISONVIEW_H_

#include "MantidQtCustomInterfaces/DataComparison/IDataComparisonView.h"

//----------------------
// Includes
//----------------------
#include "ui_DataComparisonView.h"
#include "MantidQtAPI/UserSubWindow.h"
#include "MantidQtAPI/WorkspaceObserver.h"
#include "MantidAPI/MatrixWorkspace_fwd.h"

#include <memory>

#include <qwt_plot.h>
#include <qwt_plot_curve.h>
#include <qwt_plot_magnifier.h>
#include <qwt_plot_panner.h>
#include <qwt_plot_zoomer.h>

namespace MantidQt {
namespace CustomInterfaces {

/**
Concrete implementation of the view as in the MVP pattern. Methods defined here
will be used by the presenter to act on the view.

Copyright &copy; 2016 ISIS Rutherford Appleton Laboratory, NScD
Oak Ridge National Laboratory & European Spallation Source

This file is part of Mantid.

Mantid is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

Mantid is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

File change history is stored at: <https://github.com/mantidproject/mantid>
Code Documentation is available at: <http://doxygen.mantidproject.org>
*/

class IDataComparisonPresenter;

class DataComparisonView
    : public MantidQt::API::UserSubWindow,
      public MantidQt::API::WorkspaceObserver,
      public MantidQt::CustomInterfaces::IDataComparisonView {
  Q_OBJECT

public:
  /// The name of the interface as registered into the factory
  static std::string name() { return "Data Comparison"; }
  // This interface's categories.
  static QString categoryInfo() { return "General"; }

public:
  /// Constructor
  DataComparisonView(QWidget *parent = 0);

  /// Methods inherited from IDataComparisonView
  /// Print error message
  void printError(const std::string &message) override;
  /// Print information message
  void printInformation(const std::string &message) override;
  /// Pring debug message
  void printDebug(const std::string &message) override;

  /// Tests if a workspace is shown in the UI
  bool containsWorkspace(Mantid::API::MatrixWorkspace_const_sptr ws);

private slots:
  /// Add selected data to plot
  void addData();
  /// Remove selected data from plot
  void removeSelectedData();
  /// Remove all data from plot
  void removeAllData();
  /// Create a diff of the two selected workspaces
  void diffSelected();
  /// Remove the diff from the plot
  void clearDiff();
  /// Handles replotting workspace spectra
  void plotWorkspaces();
  /// Handles updating the plot
  void updatePlot();
  /// Handles updating th eplot after a spectum index is changed
  void workspaceIndexChanged();
  /// Handles creating and plotting a diff worksapce
  void plotDiffWorkspace();
  /// Toggle the pan plot tool
  void togglePan(bool enabled);
  /// Toggle the zoom plot tool
  void toggleZoom(bool enabled);
  /// Resets the zoom level to show all curves
  void resetView();

private:
  /// Enumeration for column index
  enum Column { COLOUR, WORKSPACE_NAME, SPEC_OFFSET, CURRENT_SPEC };

  /// Initialize the layout
  void initLayout() override;
  /// Adds a workspace to the data table
  void addDataItem(Mantid::API::Workspace_const_sptr ws);
  /// Normalises spectra offsets in table
  void normaliseSpectraOffsets();
  /// Gets an initial curve colour for a new workspace
  int getInitialColourIndex();
  /// The presenter
  std::unique_ptr<IDataComparisonPresenter> m_presenter;

private:
  // Handlers for ADS events
  void
  preDeleteHandle(const std::string &wsName,
                  const boost::shared_ptr<Mantid::API::Workspace> ws) override;
  void renameHandle(const std::string &oldName,
                    const std::string &newName) override;
  void afterReplaceHandle(
      const std::string &wsName,
      const boost::shared_ptr<Mantid::API::Workspace> ws) override;

  // The form generated by Qt Designer
  Ui::DataComparisonView m_uiForm;

  // The plot object
  QwtPlot *m_plot;
  // Curves shown on plot, indexed by workspace name
  QMap<QString, boost::shared_ptr<QwtPlotCurve>> m_curves;

  // Plot zoom tool
  QwtPlotZoomer *m_zoomTool;
  // Plot pan tool
  QwtPlotPanner *m_panTool;
  // Plot magnify tool
  QwtPlotMagnifier *m_magnifyTool;

  boost::shared_ptr<QwtPlotCurve> m_diffCurve;
  // The two workspaces that are currently being diffed
  QPair<QString, QString> m_diffWorkspaceNames;
};
}
}

#endif // MANTIDQTCUSTOMINTERFACES_DATACOMPARISONVIEW_H_
